ORDWAY_APP_DOMAIN = "api.ordwaylabs.com"
ORDWAY_APP_URL = f"https://{ORDWAY_APP_DOMAIN}"

ORDWAY_SANDBOX_DOMAIN = "api.sandbox.ordwaylabs.com"
ORDWAY_SANDBOX_URL = f"https://{ORDWAY_SANDBOX_DOMAIN}"

API_ENDPOINT_BASE = f"{ORDWAY_APP_URL}/api"
SANDBOX_ENDPOINT_BASE = f"{ORDWAY_SANDBOX_URL}/api"

SUPPORTED_API_VERSIONS = ("1",)
